PROFILES_DIR = "profiles"

ACTIONABLE_THRESHOLD = 60
KEEP_THRESHOLD = 30
ARCHIVE_THRESHOLD = 20

MAX_ACTIONABLE = 50
TRASH_RETENTION_DAYS = 7

AUTO_TRASH_CATEGORIES = ["🏢_institutions", "🤖_bots"]
MIN_BALANCE_USD = 10000
MIN_CONFIDENCE = 25

STALE_DATA_DAYS = 30
INACTIVE_WALLET_DAYS = 90

